version: 2

formats:
  - pdf
  - epub
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  apt_packages:
    # XeLaTeX & friends
    - texlive-xetex
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-xindy          # NEW — fixes the indexing crash
    - texlive-lang-european  # NEW — provides LATIN9‑LANG.XDY etc.
    - latexmk
    - fonts-dejavu           # wide Unicode coverage (optional)

  commands:
    # 1️⃣  Python dependencies
    - pip install -r docs/requirements.txt

    # 2️⃣  Private package
    - pip install "git+https://${GH_PAT}@github.com/stephen-itschner/coexistence_simulator.git@main#egg=coexistence_simulator"

    # 3️⃣  HTML
    - python -m sphinx.cmd.build -b html docs/source $READTHEDOCS_OUTPUT/html

    # 4️⃣  LaTeX sources (XeLaTeX engine)
    - python -m sphinx.cmd.build -b latex -D latex_engine=xelatex docs/source $READTHEDOCS_OUTPUT/latex

    # 5️⃣  PDF via latexmk + XeLaTeX (+ xindy now available)
    - |
      cd $READTHEDOCS_OUTPUT/latex && \
      latexmk -quiet -xelatex -f coexistencesimulator.tex

    # 6️⃣  ePub & zipped‑HTML
    - python -m sphinx.cmd.build -b epub    docs/source $READTHEDOCS_OUTPUT/epub
    - python -m sphinx.cmd.build -b htmlzip docs/source $READTHEDOCS_OUTPUT/htmlzip

sphinx:
  configuration: docs/source/conf.py
