# .readthedocs.yaml  – builds HTML + PDF + EPUB + HTML‑zip
version: 2

formats: [pdf, epub, htmlzip]

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:          # TeX for the PDF
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-xetex
    - latexmk             

python:
  install:
    - requirements: docs/requirements.txt          # Sphinx + extensions
    - method: pip                                  # your private package
      path: .
      extra_requirements: [docs]                   # or omit if unused
      url: "https://${GH_PAT}@github.com/stephen-itschner/coexistence_simulator.git@main"

sphinx:
  configuration: docs/source/conf.py
