# .readthedocs.yaml ― RTD config: HTML + PDF + EPUB + HTML‑zip
version: 2

# ── 1️⃣  Extra output formats ──────────────────────────────────────────────
formats:
  - pdf          # Sphinx → LaTeX → PDF (RTD will call latexmk for you)
  - epub         # .epub ebook
  - htmlzip      # zipped HTML

# ── 2️⃣  Build environment ─────────────────────────────────────────────────
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  # Minimal LaTeX tool‑chain for XeTeX‑based PDF builds
  apt_packages:
    - texlive-xetex   # engine + base packages
    - latexmk         # RTD’s PDF helper calls this internally

# ── 3️⃣  Python dependencies ───────────────────────────────────────────────
python:
  install:
    # Docs requirements (brings in Sphinx and friends)
    - requirements: docs/requirements.txt

    # Private library under test (requires GH_PAT set in RTD → Admin → Env Vars)
    - method: pip
      path: "git+https://${GH_PAT}@github.com/stephen-itschner/coexistence_simulator.git@main#egg=coexistence_simulator"

# ── 4️⃣  Sphinx entry‑point ────────────────────────────────────────────────
sphinx:
  configuration: docs/source/conf.py
