# .readthedocs.yaml  – replace the whole file with this
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  # Everything below runs *inside* RTD’s virtual‑env
  commands:
    # 1 install your private package
    - pip install "git+https://${GH_PAT}@github.com/stephen-itschner/coexistence_simulator.git@main#egg=coexistence_simulator"

    # 2 run Sphinx and write straight to the directory RTD expects
    - sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html

python:
  install:
    - requirements: docs/requirements.txt   # Sphinx + extensions only
