# .readthedocs.yaml ── streamlined for RTD
version: 2

# 1️⃣  Tell RTD which extra output formats you want
formats:
  - pdf          # Sphinx → LaTeX → PDF (uses latexmk for you)
  - epub
  - htmlzip

# 2️⃣  Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  # LaTeX needs XeTeX and latexmk; everything else comes with RTD’s base image
  apt_packages:
    - texlive-xetex
    - latexmk

# 3️⃣  Python dependencies (RTD will run these for you)
python:
  install:
    # project itself (the repo being built):
    - method: pip
      path: .
    # requirements the docs need:
    - requirements: docs/requirements.txt
    # private GitHub package (make sure GH_PAT is set in RTD → Admin → Environment Variables)
    - method: pip
      path: "git+https://${GH_PAT}@github.com/stephen-itschner/coexistence_simulator.git@main#egg=coexistence_simulator"

# 4️⃣  Sphinx entry‑point
sphinx:
  configuration: docs/source/conf.py
