version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: "git+https://${GH_PAT}@github.com/itschner/coexistence_simulator.git@main#egg=coexistence_simulator"