# .readthedocs.yaml  ── minimal but complete
version: 2

# ❶  Extra artefacts you want besides ordinary HTML
formats:
  - pdf
  - epub
  - htmlzip

# ❷  Build image – XeTeX + latexmk are the only extra APT packages needed
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - texlive-xetex     # XeLaTeX engine
    - latexmk           # drives the LaTeX → PDF pass
  commands:
    # ---- Python deps for the *docs* themselves ----------------------------
    - pip install -r docs/requirements.txt
    # ---- Your actual library (private GitHub repo) ------------------------
    #      • Add GH_PAT as an *Environment Variable* in RTD → Admin
    - pip install "git+https://${GH_PAT}@github.com/stephen-itschner/coexistence_simulator.git@main#egg=coexistence_simulator"

# ❸  Tell RTD **not** to run “pip install .” on this repo (it’s docs‑only)
python:
  setup_py_install: false   # skip the implicit `pip install .`
  install: []               # nothing else here; everything is in `build.commands`

# ❹  Where your Sphinx config lives
sphinx:
  configuration: docs/source/conf.py
