version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  # Extra commands that run **after** the virtual‑env is created
  commands:
    # Install the private repo using the PAT you added to RTD’s env‑vars
    - pip install "git+https://${GH_PAT}@github.com/stephen-itschner/coexistence_simulator.git@main#egg=coexistence_simulator"

sphinx:
  configuration: docs/source/conf.py
  builder: html

python:
  install:
    - requirements: docs/requirements.txt    # only the Sphinx deps live here
