# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  commands:
    # 1.  install Sphinx + extensions *first*
    - pip install -r docs/requirements.txt

    # 2.  install your private package
    - pip install "git+https://${GH_PAT}@github.com/stephen-itschner/coexistence_simulator.git@main#egg=coexistence_simulator"

    # 3.  run Sphinx directly through the interpreter
    - python -m sphinx.cmd.build -b html docs/source $READTHEDOCS_OUTPUT/html
