version: 2

# ✅ Enable offline formats
formats:
  - pdf
  - epub
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  commands:
    # 1️⃣ Install Sphinx + extensions
    - pip install -r docs/requirements.txt
    # 2️⃣ Install the private package
    - pip install "git+https://${GH_PAT}@github.com/stephen-itschner/coexistence_simulator.git@main#egg=coexistence_simulator"
    # 3️⃣ Build HTML
    - python -m sphinx.cmd.build -b html docs/source $READTHEDOCS_OUTPUT/html

# Specify Sphinx configuration explicitly
sphinx:
  configuration: docs/source/conf.py
