# .readthedocs.yaml ── slim & RTD-compliant
version: 2

# extra outputs
formats: [pdf, epub, htmlzip]

# build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - texlive-xetex   # XeLaTeX engine for the PDF builder
    - latexmk         # runs the LaTeX-→-PDF pass
  commands:
    # docs’ own Python deps
    - pip install -r docs/requirements.txt
    # your *private* library (needs GH_PAT in RTD → Admin → Environment Vars)
    - pip install "git+https://${GH_PAT}@github.com/stephen-itschner/coexistence_simulator.git@main#egg=coexistence_simulator"

# tell RTD **not** to run “pip install .” on this repo
python:
  install: []   # an empty list disables the default step

# where Sphinx’s conf.py lives
sphinx:
  configuration: docs/source/conf.py
