# .readthedocs.yaml  –  builds HTML + PDF + EPUB + HTML‑zip
version: 2

formats:
  - pdf
  - epub
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  apt_packages:        # only the basics; we no longer need full xindy support
    - texlive-xetex
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - latexmk            # still needed for the manual PDF pass

  commands:
    # 1️⃣  Python deps
    - pip install -r docs/requirements.txt
    # 2️⃣  Private package
    - pip install "git+https://${GH_PAT}@github.com/stephen-itschner/coexistence_simulator.git@main#egg=coexistence_simulator"

    # 3️⃣  Build HTML
    - python -m sphinx -b html docs/source $READTHEDOCS_OUTPUT/html

    # 4️⃣  Build LaTeX sources **without xindy**
    - python -m sphinx -b latex -D latex_engine=xelatex -D latex_use_xindy=0 docs/source $READTHEDOCS_OUTPUT/latex

    # 5️⃣  Turn LaTeX into PDF
    - cd $READTHEDOCS_OUTPUT/latex && latexmk -quiet -xelatex -f coexistencesimulator.tex

    # 6️⃣  Build EPUB & zipped‑HTML
    - python -m sphinx -b epub    docs/source $READTHEDOCS_OUTPUT/epub
    - python -m sphinx -b htmlzip docs/source $READTHEDOCS_OUTPUT/htmlzip

sphinx:
  configuration: docs/source/conf.py
